<template>
  <main>
    <span>Vue.js Project Generated by Pygen</span>
  </main>
</template>

<script setup lang="ts"></script>

<style scoped>
main {
  text-align: center;
  height: 100vh;
  line-height: 100vh;
}
span {
  font-size: 28px;
  font-weight: bold;
  color: #64748b;
}
</style>
